apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: instagram-clone/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "."
            src: "src/**/*.ts"
    - image: instagram-clone/profile
      context: profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "."
            src: "src/**/*.ts"
