apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: instagram-clone/profile
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: profile-mongo-config-map
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: profile-mongo-config-map
                  key: db-name
            - name: MEMBER_BASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: profile-mongo-config-map
                  key: member-base-name
            - name: REPLSET_NAME
              valueFrom:
                configMapKeyRef:
                  name: profile-mongo-config-map
                  key: replset-name
            - name: LOCAL_KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-config-map
                  key: url
---
apiVersion: v1
kind: Service
metadata:
  name: profile-cluster-ip
spec:
  selector:
    app: profile
  ports:
    - name: profile
      protocol: TCP
      port: 3000
      targetPort: 3000
