apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-mongo-config-map
data:
  host: profile-mongo-svc.default.svc.cluster.local:27017
  db-name: profile
  member-base-name: profile-mongo
  replset-name: profile-mongo