apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-mongo
  template:
    metadata:
      labels:
        app: profile-mongo
    spec:
      containers:
        - name: profile-mongo
          image: mongo
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - "rs0"
            #after pod initialization, use rs.initiate() to
            #start the replicaSet in the pod mongosh terminal
---
apiVersion: v1
kind: Service
metadata:
  name: profile-mongo-cluster-ip
spec:
  selector:
    app: profile-mongo
  ports:
    - name: profile-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
