apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: instagram-clone/auth
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-mongo-config-map
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-mongo-config-map
                  key: db-name
            - name: MEMBER_BASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-mongo-config-map
                  key: member-base-name
            - name: REPLSET_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-mongo-config-map
                  key: replset-name
            - name: LOCAL_KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-config-map
                  key: url
            - name: HOST_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-config-map
                  key: host-name
---
apiVersion: v1
kind: Service
metadata:
  name: auth-cluster-ip
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
